//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTussentijdsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Orderlijnens = new HashSet<Orderlijnen>();
        }
    
        public int OrderID { get; set; }
        public string Klantnummer { get; set; }
        public Nullable<int> WerknemerID { get; set; }
        public Nullable<System.DateTime> Orderdatum { get; set; }
        public string VerzendBedrijf { get; set; }
        public string Verzendadres { get; set; }
        public string Verzendplaats { get; set; }
        public string Verzendpostcode { get; set; }
        public string Verzendland { get; set; }
    
        public virtual Klanten Klanten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderlijnen> Orderlijnens { get; set; }
        public virtual Werknemer Werknemer { get; set; }
    }
}
